program compTestZAI134;

{$APPTYPE CONSOLE}

{$R *.res}


uses
  (*system unit*)
  System.SysUtils,

  (*..\Source*)
  CoreClasses in '..\Source\CoreClasses.pas',
  ListEngine in '..\Source\ListEngine.pas',
  MH_ZDB in '..\Source\MH_ZDB.pas',
  MH_1 in '..\Source\MH_1.pas',
  MH_2 in '..\Source\MH_2.pas',
  MH_3 in '..\Source\MH_3.pas',
  MH in '..\Source\MH.pas',
  h264MB_encoder in '..\Source\h264MB_encoder.pas',
  h264Motion_comp in '..\Source\h264Motion_comp.pas',
  h264Loopfilter in '..\Source\h264Loopfilter.pas',
  h264Macroblock in '..\Source\h264Macroblock.pas',
  h264Motion_est in '..\Source\h264Motion_est.pas',
  h264Pixel in '..\Source\h264Pixel.pas',
  h264RateControl in '..\Source\h264RateControl.pas',
  h264motion_est_search in '..\Source\h264motion_est_search.pas',
  h264Parameters in '..\Source\h264Parameters.pas',
  h264BitStream in '..\Source\h264BitStream.pas',
  h264Common in '..\Source\h264Common.pas',
  GeometryRotationUnit in '..\Source\GeometryRotationUnit.pas',
  h264 in '..\Source\h264.pas',
  h264Encoder in '..\Source\h264Encoder.pas',
  h264inter_pred in '..\Source\h264inter_pred.pas',
  h264Intra_pred in '..\Source\h264Intra_pred.pas',
  h264Frame in '..\Source\h264Frame.pas',
  h264Image in '..\Source\h264Image.pas',
  JLSCodec in '..\Source\JLSCodec.pas',
  JLSDecoder in '..\Source\JLSDecoder.pas',
  JLSBaseCodec in '..\Source\JLSBaseCodec.pas',
  JLSBitIO in '..\Source\JLSBitIO.pas',
  JLSEncoder in '..\Source\JLSEncoder.pas',
  JLSLossless in '..\Source\JLSLossless.pas',
  JLSLossy in '..\Source\JLSLossy.pas',
  JLSGlobal in '..\Source\JLSGlobal.pas',
  JLSJpegmark in '..\Source\JLSJpegmark.pas',
  h264tables in '..\Source\h264tables.pas',
  h264Transquant in '..\Source\h264Transquant.pas',
  h264Stats in '..\Source\h264Stats.pas',
  h264stream in '..\Source\h264stream.pas',
  h264Types in '..\Source\h264Types.pas',
  HostQuery in '..\Source\HostQuery.pas',
  ItemStream in '..\Source\ItemStream.pas',
  h264Util in '..\Source\h264Util.pas',
  h264VLC in '..\Source\h264VLC.pas',
  GeometryLib in '..\Source\GeometryLib.pas',
  DistortionRaster in '..\Source\DistortionRaster.pas',
  DoStatusIO in '..\Source\DoStatusIO.pas',
  CoreCompress in '..\Source\CoreCompress.pas',
  DataFrameEngine in '..\Source\DataFrameEngine.pas',
  Fast_MD5 in '..\Source\Fast_MD5.pas',
  FastKDTreeC in '..\Source\FastKDTreeC.pas',
  FastKDTreeD in '..\Source\FastKDTreeD.pas',
  FastGBK in '..\Source\FastGBK.pas',
  FastHistogramSpace in '..\Source\FastHistogramSpace.pas',
  CommunicationFrameworkDoubleTunnelIO_NoAuth in '..\Source\CommunicationFrameworkDoubleTunnelIO_NoAuth.pas',
  CommunicationFrameworkDoubleTunnelIO_ServMan in '..\Source\CommunicationFrameworkDoubleTunnelIO_ServMan.pas',
  CommunicationFrameworkDataStoreServiceCommon in '..\Source\CommunicationFrameworkDataStoreServiceCommon.pas',
  CommunicationFrameworkDoubleTunnelIO in '..\Source\CommunicationFrameworkDoubleTunnelIO.pas',
  CommunicationFrameworkDoubleTunnelIO_VirtualAuth in '..\Source\CommunicationFrameworkDoubleTunnelIO_VirtualAuth.pas',
  CoreCipher in '..\Source\CoreCipher.pas',
  CommunicationFrameworkIO in '..\Source\CommunicationFrameworkIO.pas',
  CommunicationTest in '..\Source\CommunicationTest.pas',
  FPCGenericStructlist in '..\Source\FPCGenericStructlist.pas',
  GBK in '..\Source\GBK.pas',
  FileIndexPackage in '..\Source\FileIndexPackage.pas',
  FilePackage in '..\Source\FilePackage.pas',
  GBKBig in '..\Source\GBKBig.pas',
  Geometry2DUnit in '..\Source\Geometry2DUnit.pas',
  Geometry3DUnit in '..\Source\Geometry3DUnit.pas',
  GBKMediaCenter in '..\Source\GBKMediaCenter.pas',
  GBKVec in '..\Source\GBKVec.pas',
  FastKDTreeI16 in '..\Source\FastKDTreeI16.pas',
  FastKDTreeI32 in '..\Source\FastKDTreeI32.pas',
  FastKDTreeE in '..\Source\FastKDTreeE.pas',
  FastKDTreeI8 in '..\Source\FastKDTreeI8.pas',
  FastKDTreeI64 in '..\Source\FastKDTreeI64.pas',
  FFMPEG_Reader in '..\Source\FFMPEG_Reader.pas',
  FFMPEG_Writer in '..\Source\FFMPEG_Writer.pas',
  FastKDTreeS in '..\Source\FastKDTreeS.pas',
  FFMPEG in '..\Source\FFMPEG.pas',
  zAI_Common in '..\Source\zAI_Common.pas',
  zAI_Editor_Common in '..\Source\zAI_Editor_Common.pas',
  Y4M in '..\Source\Y4M.pas',
  zAI in '..\Source\zAI.pas',
  zAI_ExtractVideoFace in '..\Source\zAI_ExtractVideoFace.pas',
  zAI_TrainingTask in '..\Source\zAI_TrainingTask.pas',
  zAI_VideoFaceQueue in '..\Source\zAI_VideoFaceQueue.pas',
  zAI_FFMPEG in '..\Source\zAI_FFMPEG.pas',
  zAI_KeyIO in '..\Source\zAI_KeyIO.pas',
  TextTable in '..\Source\TextTable.pas',
  UnicodeMixedLib in '..\Source\UnicodeMixedLib.pas',
  TextDataEngine in '..\Source\TextDataEngine.pas',
  TextParsing in '..\Source\TextParsing.pas',
  UPascalStrings in '..\Source\UPascalStrings.pas',
  XNATPhysics in '..\Source\XNATPhysics.pas',
  XNATService in '..\Source\XNATService.pas',
  XNATClient in '..\Source\XNATClient.pas',
  XNATMappingOnVirutalService in '..\Source\XNATMappingOnVirutalService.pas',
  ZIOThread in '..\Source\ZIOThread.pas',
  zNavigationPass in '..\Source\zNavigationPass.pas',
  zDrawEngineSoftY4M in '..\Source\zDrawEngineSoftY4M.pas',
  zExpression in '..\Source\zExpression.pas',
  zNavigationPathFinding in '..\Source\zNavigationPathFinding.pas',
  ZS_JsonDataObjects in '..\Source\ZS_JsonDataObjects.pas',
  zSound in '..\Source\zSound.pas',
  zNavigationPoly in '..\Source\zNavigationPoly.pas',
  zNavigationScene in '..\Source\zNavigationScene.pas',
  ZDB2_Core in '..\Source\ZDB2_Core.pas',
  ZDB2_FileEncoder in '..\Source\ZDB2_FileEncoder.pas',
  zAI_VideoRasterDNNThreadQueue in '..\Source\zAI_VideoRasterDNNThreadQueue.pas',
  ZDB2 in '..\Source\ZDB2.pas',
  ZDBEngine in '..\Source\ZDBEngine.pas',
  zDrawEngine in '..\Source\zDrawEngine.pas',
  zDrawEngineSoftH264 in '..\Source\zDrawEngineSoftH264.pas',
  ZDBLocalManager in '..\Source\ZDBLocalManager.pas',
  ZDBVideoStoreFormula in '..\Source\ZDBVideoStoreFormula.pas',
  Raster_PNG in '..\Source\Raster_PNG.pas',
  MemoryStream64 in '..\Source\MemoryStream64.pas',
  MorphologyExpression in '..\Source\MorphologyExpression.pas',
  MemoryRaster_DocumentTextDetector in '..\Source\MemoryRaster_DocumentTextDetector.pas',
  MemoryRaster_Motion in '..\Source\MemoryRaster_Motion.pas',
  MovementEngine in '..\Source\MovementEngine.pas',
  ObjectData in '..\Source\ObjectData.pas',
  ObjectDataHashField in '..\Source\ObjectDataHashField.pas',
  NotifyObjectBase in '..\Source\NotifyObjectBase.pas',
  NumberBase in '..\Source\NumberBase.pas',
  KM in '..\Source\KM.pas',
  Learn in '..\Source\Learn.pas',
  JLSMelcode in '..\Source\JLSMelcode.pas',
  KDTree in '..\Source\KDTree.pas',
  LearnTypes in '..\Source\LearnTypes.pas',
  MediaCenter in '..\Source\MediaCenter.pas',
  MemoryRaster in '..\Source\MemoryRaster.pas',
  LinearAction in '..\Source\LinearAction.pas',
  Raster_JPEG_DICT in '..\Source\Raster_JPEG_DICT.pas',
  Raster_JPEG_Huffman in '..\Source\Raster_JPEG_Huffman.pas',
  Raster_JPEG_Coder in '..\Source\Raster_JPEG_Coder.pas',
  Raster_JPEG_ColorTransforms in '..\Source\Raster_JPEG_ColorTransforms.pas',
  Raster_JPEG_Image in '..\Source\Raster_JPEG_Image.pas',
  Raster_JPEG_Marker in '..\Source\Raster_JPEG_Marker.pas',
  Raster_JPEG_type in '..\Source\Raster_JPEG_type.pas',
  Raster_JPEG_Lossless in '..\Source\Raster_JPEG_Lossless.pas',
  Raster_JPEG_MapIterator in '..\Source\Raster_JPEG_MapIterator.pas',
  OpCode in '..\Source\OpCode.pas',
  PascalStrings in '..\Source\PascalStrings.pas',
  ObjectDataHashItem in '..\Source\ObjectDataHashItem.pas',
  ObjectDataManager in '..\Source\ObjectDataManager.pas',
  PhysicsIO in '..\Source\PhysicsIO.pas',
  Raster_JPEG in '..\Source\Raster_JPEG.pas',
  Raster_JPEG_BitStream in '..\Source\Raster_JPEG_BitStream.pas',
  PictureViewerInterface in '..\Source\PictureViewerInterface.pas',
  PyramidSpace in '..\Source\PyramidSpace.pas',
  AggPathStorageInteger in '..\Source\AggPathStorageInteger.pas',
  AggPatternFiltersRgba in '..\Source\AggPatternFiltersRgba.pas',
  AggMathStroke in '..\Source\AggMathStroke.pas',
  AggPathStorage in '..\Source\AggPathStorage.pas',
  AggPixelFormat in '..\Source\AggPixelFormat.pas',
  AggPixelFormatRgb in '..\Source\AggPixelFormatRgb.pas',
  AggPixelFormatRgba in '..\Source\AggPixelFormatRgba.pas',
  AggPixelFormatAlphaMaskAdaptor in '..\Source\AggPixelFormatAlphaMaskAdaptor.pas',
  AggPixelFormatGray in '..\Source\AggPixelFormatGray.pas',
  AggEllipseBresenham in '..\Source\AggEllipseBresenham.pas',
  AggGammaFunctions in '..\Source\AggGammaFunctions.pas',
  AggDdaLine in '..\Source\AggDdaLine.pas',
  AggEllipse in '..\Source\AggEllipse.pas',
  AggGammaLUT in '..\Source\AggGammaLUT.pas',
  AggLineAABasics in '..\Source\AggLineAABasics.pas',
  AggMath in '..\Source\AggMath.pas',
  AggGradientLut in '..\Source\AggGradientLut.pas',
  AggImageFilters in '..\Source\AggImageFilters.pas',
  AggRendererMarkers in '..\Source\AggRendererMarkers.pas',
  AggRendererMultiClip in '..\Source\AggRendererMultiClip.pas',
  AggRasterizerScanlineClip in '..\Source\AggRasterizerScanlineClip.pas',
  AggRendererBase in '..\Source\AggRendererBase.pas',
  AggRendererOutlineAA in '..\Source\AggRendererOutlineAA.pas',
  AggRendererScanLine in '..\Source\AggRendererScanLine.pas',
  AggRenderingBuffer in '..\Source\AggRenderingBuffer.pas',
  AggRendererOutlineImage in '..\Source\AggRendererOutlineImage.pas',
  AggRendererPrimitives in '..\Source\AggRendererPrimitives.pas',
  AggQuadratureOscillator in '..\Source\AggQuadratureOscillator.pas',
  AggRasterizerCellsAA in '..\Source\AggRasterizerCellsAA.pas',
  AggPixelFormatRgbPacked in '..\Source\AggPixelFormatRgbPacked.pas',
  AggPixelFormatTransposer in '..\Source\AggPixelFormatTransposer.pas',
  AggRasterizerCompoundAA in '..\Source\AggRasterizerCompoundAA.pas',
  AggRasterizerScanLine in '..\Source\AggRasterizerScanLine.pas',
  AggRasterizerScanLineAA in '..\Source\AggRasterizerScanLineAA.pas',
  AggRasterizerOutline in '..\Source\AggRasterizerOutline.pas',
  AggRasterizerOutlineAA in '..\Source\AggRasterizerOutlineAA.pas',
  AggCurves in '..\Source\AggCurves.pas',
  AggBezierArc in '..\Source\AggBezierArc.pas',
  AggBitsetIterator in '..\Source\AggBitsetIterator.pas',
  AggArrowHead in '..\Source\AggArrowHead.pas',
  AggBasics in '..\Source\AggBasics.pas',
  AggBlur in '..\Source\AggBlur.pas',
  AggClipLiangBarsky in '..\Source\AggClipLiangBarsky.pas',
  AggColor32 in '..\Source\AggColor32.pas',
  AggBoundingRect in '..\Source\AggBoundingRect.pas',
  AggBSpline in '..\Source\AggBSpline.pas',
  AggArc in '..\Source\AggArc.pas',
  AggArray in '..\Source\AggArray.pas',
  Agg2D in '..\Source\Agg2D.pas',
  AggAlphaMaskUnpacked8 in '..\Source\AggAlphaMaskUnpacked8.pas',
  AggConvMarker in '..\Source\AggConvMarker.pas',
  AggConvMarkerAdaptor in '..\Source\AggConvMarkerAdaptor.pas',
  AggConvCurve in '..\Source\AggConvCurve.pas',
  AggConvDash in '..\Source\AggConvDash.pas',
  AggConvSegmentator in '..\Source\AggConvSegmentator.pas',
  AggConvStroke in '..\Source\AggConvStroke.pas',
  AggConvTransform in '..\Source\AggConvTransform.pas',
  AggConvShortenPath in '..\Source\AggConvShortenPath.pas',
  AggConvSmoothPoly in '..\Source\AggConvSmoothPoly.pas',
  AggConvAdaptorVcgen in '..\Source\AggConvAdaptorVcgen.pas',
  AggConvAdaptorVpgen in '..\Source\AggConvAdaptorVpgen.pas',
  AggColorConversion in '..\Source\AggColorConversion.pas',
  AggControl in '..\Source\AggControl.pas',
  AggConvBSpline in '..\Source\AggConvBSpline.pas',
  AggConvConcat in '..\Source\AggConvConcat.pas',
  AggConvContour in '..\Source\AggConvContour.pas',
  AggConvClipPolygon in '..\Source\AggConvClipPolygon.pas',
  AggConvClipPolyline in '..\Source\AggConvClipPolyline.pas',
  AggTransDoublePath in '..\Source\AggTransDoublePath.pas',
  AggTransPerspective in '..\Source\AggTransPerspective.pas',
  AggTransAffine in '..\Source\AggTransAffine.pas',
  AggTransBilinear in '..\Source\AggTransBilinear.pas',
  AggTransSinglePath in '..\Source\AggTransSinglePath.pas',
  AggVcgenBSpline in '..\Source\AggVcgenBSpline.pas',
  AggVcgenContour in '..\Source\AggVcgenContour.pas',
  AggTransViewport in '..\Source\AggTransViewport.pas',
  AggTransWarpMagnifier in '..\Source\AggTransWarpMagnifier.pas',
  AggSpanPatternResampleRgb in '..\Source\AggSpanPatternResampleRgb.pas',
  AggSpanPatternResampleRgba in '..\Source\AggSpanPatternResampleRgba.pas',
  AggSpanPatternFilterRgba in '..\Source\AggSpanPatternFilterRgba.pas',
  AggSpanPatternResampleGray in '..\Source\AggSpanPatternResampleGray.pas',
  AggSpanPatternRgb in '..\Source\AggSpanPatternRgb.pas',
  AggSpanSubdivAdaptor in '..\Source\AggSpanSubdivAdaptor.pas',
  AggSpiral in '..\Source\AggSpiral.pas',
  AggSpanPatternRgba in '..\Source\AggSpanPatternRgba.pas',
  AggSpanSolid in '..\Source\AggSpanSolid.pas',
  AudioPrint in '..\Source\AudioPrint.pas',
  BulletMovementEngine in '..\Source\BulletMovementEngine.pas',
  AggVpGenClipPolyline in '..\Source\AggVpGenClipPolyline.pas',
  AggVpGenSegmentator in '..\Source\AggVpGenSegmentator.pas',
  Cadencer in '..\Source\Cadencer.pas',
  CommunicationFrameworkDataStoreService_NoAuth in '..\Source\CommunicationFrameworkDataStoreService_NoAuth.pas',
  CommunicationFrameworkDataStoreService_VirtualAuth in '..\Source\CommunicationFrameworkDataStoreService_VirtualAuth.pas',
  CommunicationFramework in '..\Source\CommunicationFramework.pas',
  CommunicationFrameworkDataStoreService in '..\Source\CommunicationFrameworkDataStoreService.pas',
  AggVcgenSmoothPoly1 in '..\Source\AggVcgenSmoothPoly1.pas',
  AggVcgenStroke in '..\Source\AggVcgenStroke.pas',
  AggVcgenDash in '..\Source\AggVcgenDash.pas',
  AggVcgenMarkersTerm in '..\Source\AggVcgenMarkersTerm.pas',
  AggVcgenVertexSequence in '..\Source\AggVcgenVertexSequence.pas',
  AggVpGen in '..\Source\AggVpGen.pas',
  AggVpGenClipPolygon in '..\Source\AggVpGenClipPolygon.pas',
  AggVertexSequence in '..\Source\AggVertexSequence.pas',
  AggVertexSource in '..\Source\AggVertexSource.pas',
  AggSpanPatternFilterRgb in '..\Source\AggSpanPatternFilterRgb.pas',
  AggSimulEq in '..\Source\AggSimulEq.pas',
  AggSpanAllocator in '..\Source\AggSpanAllocator.pas',
  AggScanlineUnpacked in '..\Source\AggScanlineUnpacked.pas',
  AggShortenPath in '..\Source\AggShortenPath.pas',
  AggSpanConverter in '..\Source\AggSpanConverter.pas',
  AggSpanGouraudGray in '..\Source\AggSpanGouraudGray.pas',
  AggSpanGouraudRgba in '..\Source\AggSpanGouraudRgba.pas',
  AggSpanGenerator in '..\Source\AggSpanGenerator.pas',
  AggSpanGouraud in '..\Source\AggSpanGouraud.pas',
  AggRoundedRect in '..\Source\AggRoundedRect.pas',
  AggScanline in '..\Source\AggScanline.pas',
  AggRenderingBufferDynaRow in '..\Source\AggRenderingBufferDynaRow.pas',
  AggRenderScanlines in '..\Source\AggRenderScanlines.pas',
  AggScanlineBin in '..\Source\AggScanlineBin.pas',
  AggScanlineStorageAA in '..\Source\AggScanlineStorageAA.pas',
  AggScanlineStorageBin in '..\Source\AggScanlineStorageBin.pas',
  AggScanlineBooleanAlgebra in '..\Source\AggScanlineBooleanAlgebra.pas',
  AggScanlinePacked in '..\Source\AggScanlinePacked.pas',
  AggSpanImageResampleRgba in '..\Source\AggSpanImageResampleRgba.pas',
  AggSpanInterpolatorAdaptor in '..\Source\AggSpanInterpolatorAdaptor.pas',
  AggSpanImageResampleGray in '..\Source\AggSpanImageResampleGray.pas',
  AggSpanImageResampleRgb in '..\Source\AggSpanImageResampleRgb.pas',
  AggSpanInterpolatorLinear in '..\Source\AggSpanInterpolatorLinear.pas',
  AggSpanPattern in '..\Source\AggSpanPattern.pas',
  AggSpanPatternFilterGray in '..\Source\AggSpanPatternFilterGray.pas',
  AggSpanInterpolatorPerspective in '..\Source\AggSpanInterpolatorPerspective.pas',
  AggSpanInterpolatorTrans in '..\Source\AggSpanInterpolatorTrans.pas',
  AggSpanGradientContour in '..\Source\AggSpanGradientContour.pas',
  AggSpanGradientImage in '..\Source\AggSpanGradientImage.pas',
  AggSpanGradient in '..\Source\AggSpanGradient.pas',
  AggSpanGradientAlpha in '..\Source\AggSpanGradientAlpha.pas',
  AggSpanImageFilter in '..\Source\AggSpanImageFilter.pas',
  AggSpanImageFilterRgba in '..\Source\AggSpanImageFilterRgba.pas',
  AggSpanImageResample in '..\Source\AggSpanImageResample.pas',
  AggSpanImageFilterGray in '..\Source\AggSpanImageFilterGray.pas',
  AggSpanImageFilterRgb in '..\Source\AggSpanImageFilterRgb.pas',

  (*..\Source\CrossSocket*)
  CommunicationFramework_Server_CrossSocket in '..\Source\CrossSocket\CommunicationFramework_Server_CrossSocket.pas',
  CommunicationFramework_Client_CrossSocket in '..\Source\CrossSocket\CommunicationFramework_Client_CrossSocket.pas',

  (*..\Source\DIOCP*)
  CommunicationFramework_Client_DIOCP in '..\Source\DIOCP\CommunicationFramework_Client_DIOCP.pas',
  CommunicationFramework_Server_DIOCP in '..\Source\DIOCP\CommunicationFramework_Server_DIOCP.pas',

  (*..\Source\DrawInterfaceInFMX*)
  zDrawControlBoxForFMX in '..\Source\DrawInterfaceInFMX\zDrawControlBoxForFMX.pas',
  zDrawEngineInterface_FMX in '..\Source\DrawInterfaceInFMX\zDrawEngineInterface_FMX.pas',
  zDrawEngineInterface_SlowFMX in '..\Source\DrawInterfaceInFMX\zDrawEngineInterface_SlowFMX.pas',
  FMXCharacterMapBuilder in '..\Source\DrawInterfaceInFMX\FMXCharacterMapBuilder.pas',

  (*..\Source\DrawInterfaceInVCL*)
  zDrawEngineInterface_VCL in '..\Source\DrawInterfaceInVCL\zDrawEngineInterface_VCL.pas',

  (*..\Source\ICS*)
  CommunicationFramework_Server_ICS in '..\Source\ICS\CommunicationFramework_Server_ICS.pas',
  CommunicationFramework_Server_ICSCustomSocket in '..\Source\ICS\CommunicationFramework_Server_ICSCustomSocket.pas',
  CommunicationFramework_Client_ICS in '..\Source\ICS\CommunicationFramework_Client_ICS.pas',

  (*..\Source\Indy*)
  CommunicationFramework_Client_Indy in '..\Source\Indy\CommunicationFramework_Client_Indy.pas',
  CommunicationFramework_Server_Indy in '..\Source\Indy\CommunicationFramework_Server_Indy.pas',

  (*..\Source\MM*)
  Optimize.Move.Win32 in '..\Source\MM\Optimize.Move.Win32.pas',

  (*..\Source\SoundInterfaceInBass*)
  Bass in '..\Source\SoundInterfaceInBass\Bass.pas',
  zSound_Bass in '..\Source\SoundInterfaceInBass\zSound_Bass.pas',

  (*..\Source\SoundInterfaceInFMX*)
  zSound_FMX in '..\Source\SoundInterfaceInFMX\zSound_FMX.pas',

  (*..\Source\Synapse.FPC*)
  CommunicationFramework_Client_Synapse in '..\Source\Synapse.FPC\CommunicationFramework_Client_Synapse.pas',
  CommunicationFramework_Server_Synapse in '..\Source\Synapse.FPC\CommunicationFramework_Server_Synapse.pas',

  (*..\Source\developerRefrence*)
  CommunicationFramework_Client_Refrence in '..\Source\developerRefrence\CommunicationFramework_Client_Refrence.pas',
  CommunicationFramework_Server_Refrence in '..\Source\developerRefrence\CommunicationFramework_Server_Refrence.pas';

begin
  while TCompute.TotalTask > 0 do
      CheckThreadSynchronize(1);
  Writeln('press any key to exit...');
  readln;
end.
